import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { integralCF, satoshi } from "@/styles/fonts/fonts";
import TopHeader from "@/components/header/TopHeader";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import LastOffer from "@/components/offers/LastOffer";
import Container from "@/components/ui/Container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistSans.variable} ${satoshi.className} ${integralCF.variable} antialiased`}
      >
        <TopHeader />
        <Header />
        {children}
        <Container className="relative -bottom-24">
          <LastOffer />
        </Container>
        <Footer />
      </body>
    </html>
  );
}
