import type { Metadata } from "next";
import "@/styles/globals.css";
import { integralCF, satoshi } from "@/styles/fonts/fonts";
import TopHeader from "@/components/header/TopHeader";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import LastOffer from "@/components/offers/LastOffer";
import Container from "@/components/ui/Container";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} ${integralCF.variable} antialiased`}
      >
        <TopHeader />
        <Header />
        {children}
        <SanityLive />
        {(await draftMode()).isEnabled && <VisualEditing />}
        <Container className="relative -bottom-24">
          <LastOffer />
        </Container>
        <Footer />
      </body>
    </html>
  );
}
